server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          #url del repositorio donde esta ubicado los proyectos (con ello el fichero yml de ellos)
          uri: https://github.com/marianoldm/bootCampConfigService.git
          # especificamos donde esta los archivos de configuracion de nuestros proyectos
          searchPaths: config-data
          #variables de entorno para cuando subamos no este en el repositorio a la vista el user y el pass
          username: marianoldm
          password: mla04cam%
security:
  user:
    name: root
    password: s3cr3t